FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install vim git -y
RUN apt-get install netstat-nat net-tools -y

COPY ./.bash_aliases /root/.bash_aliases

COPY ./start.sh /root/start.sh
RUN chsh -s /bin/bash root

ENTRYPOINT /bin/bash /root/start.sh
